[package]
name = "hopdr"
version = "0.1.0"
authors = ["moratorium08 <moratorium08@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
z3 = "0.9.0"
