name: hopdr-test

on: [push]

defaults:
  run:
    working-directory: hopdr

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    container: moratorium08/hopdr
    steps:
    - uses: actions/checkout@v2
    - name: Add hopdr/bin to PATH
      run: echo "$GITHUB_WORKSPACE/hopdr/bin" >> $GITHUB_PATH
    # These initializations have been done in Dockerfile
    # but GitHub Actions override $HOME, and I don't know
    # what is the best way to tackle this. So, I just re-install
    # the packages here.
    - name: rust init
      run: rustup default stable
    - name: opam init
      run: opam init -a -y && eval $(opam env) && opam install -y ocamlformat dune
    - name: Format
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build
    - name: Test
      run: eval $(opam env) && cargo test --verbose
    - name: Functional Test
      run: eval $(opam env) && ./test.sh
